### ISSUE TITLE
Test case doesn't match objective

### ISSUE THREAD

**Issue by VonCrab** [rmotr-curriculum/pyp-class#1]
There's an issue with [Count Days tests](pyp-class/unit-2-data-types/lesson-7-count-days/tests.py).

The instructions state:

> Write a function that receives two date objects, and returns the amount of days that have past from one date to the other. **Make sure to check that the second date is greater than the first one**.

Yet `test_count_days_no_difference` instead tests for less than or equal.
```

def test_count_days_no_difference(self):
        days = count_days(date(2016, 1, 1),
                          date(2016, 1, 1))
        self.assertEqual(days, 0)
```

I would recommend either the instructions are updated to be inclusive for an equal date or adjust the testcase to reflect the greater than specifications.

**Comment by santiagobasulto** [comment]
+1 Thanks very much. Will fix in a second.

**Comment by santiagobasulto** [comment]
Thanks again. Fixed in https://github.com/rmotr-curriculum/pyp-class/commit/4f416a93c1c50a0f8f5c3a4fcf71ca492abf7b8e
